EKS > Add tags in all resources
opszero/kubespot pull request #133
Opened 2021-05-27 20:18 UTC by janavenkat

Here is the plan

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement
 <= read (data resources)

Terraform will perform the following actions:

  # module.opszero-eks.data.tls_certificate.cluster will be read during apply
  # (config refers to values not yet known)
 <= data "tls_certificate" "cluster"  {
      ~ certificates = [
          - {
              - is_ca                = true
              - issuer               = "OU=Starfield Class 2 Certification Authority,O=Starfield Technologies\\, Inc.,C=US"
              - not_after            = "2034-06-28T17:39:16Z"
              - not_before           = "2009-09-02T00:00:00Z"
              - public_key_algorithm = "RSA"
              - serial_number        = "12037640545166866303"
              - sha1_fingerprint     = "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
              - signature_algorithm  = "SHA256-RSA"
              - subject              = "CN=Starfield Services Root Certificate Authority - G2,O=Starfield Technologies\\, Inc.,L=Scottsdale,ST=Arizona,C=US"
              - version              = 3
            },
          - {
              - is_ca                = true
              - issuer               = "CN=Starfield Services Root Certificate Authority - G2,O=Starfield Technologies\\, Inc.,L=Scottsdale,ST=Arizona,C=US"
              - not_after            = "2037-12-31T01:00:00Z"
              - not_before           = "2015-05-25T12:00:00Z"
              - public_key_algorithm = "RSA"
              - serial_number        = "144918191876577076464031512351042010504348870"
              - sha1_fingerprint     = "06b25927c42a721631c1efd9431e648fa62e1e39"
              - signature_algorithm  = "SHA256-RSA"
              - subject              = "CN=Amazon Root CA 1,O=Amazon,C=US"
              - version              = 3
            },
          - {
              - is_ca                = true
              - issuer               = "CN=Amazon Root CA 1,O=Amazon,C=US"
              - not_after            = "2025-10-19T00:00:00Z"
              - not_before           = "2015-10-22T00:00:00Z"
              - public_key_algorithm = "RSA"
              - serial_number        = "144918209630989264145272943054026349679957517"
              - sha1_fingerprint     = "917e732d330f9a12404f73d8bea36948b929dffc"
              - signature_algorithm  = "SHA256-RSA"
              - subject              = "CN=Amazon,OU=Server CA 1B,O=Amazon,C=US"
              - version              = 3
            },
          - {
              - is_ca                = false
              - issuer               = "CN=Amazon,OU=Server CA 1B,O=Amazon,C=US"
              - not_after            = "2021-08-10T12:00:00Z"
              - not_before           = "2020-07-10T00:00:00Z"
              - public_key_algorithm = "RSA"
              - serial_number        = "11183809223080736316513154511273538306"
              - sha1_fingerprint     = "ce777ad27909e070d99eece1ff2f774624e1e7e7"
              - signature_algorithm  = "SHA256-RSA"
              - subject              = "CN=oidc.eks.us-east-1.amazonaws.com"
              - version              = 3
            },
        ] -> (known after apply)
      ~ id           = "2021-05-27 18:41:05.989465 +0000 UTC" -> (known after apply)
      - verify_chain = true -> null
        # (1 unchanged attribute hidden)
    }

  # module.opszero-eks.aws_autoscaling_group.nodes_blue will be updated in-place
  ~ resource "aws_autoscaling_group" "nodes_blue" {
        id                        = "axiom-prod-nodes-blue"
        name                      = "axiom-prod-nodes-blue"
      ~ tags                      = [
          + {
              + "key"                 = "KubespotEnvironment"
              + "propagate_at_launch" = "true"
              + "value"               = "axiom-prod"
            },
            # (4 unchanged elements hidden)
        ]
        # (23 unchanged attributes hidden)
    }

  # module.opszero-eks.aws_autoscaling_group.nodes_green will be updated in-place
  ~ resource "aws_autoscaling_group" "nodes_green" {
        id                        = "axiom-prod-nodes-green"
        name                      = "axiom-prod-nodes-green"
      ~ tags                      = [
          + {
              + "key"                 = "KubespotEnvironment"
              + "propagate_at_launch" = "true"
              + "value"               = "axiom-prod"
            },
            # (4 unchanged elements hidden)
        ]
        # (23 unchanged attributes hidden)
    }

  # module.opszero-eks.aws_cloudwatch_log_group.vpc will be updated in-place
  ~ resource "aws_cloudwatch_log_group" "vpc" {
        id                = "axiom-prod"
        name              = "axiom-prod"
      ~ tags              = {
          + "KubespotEnvironment" = "axiom-prod"
        }
      ~ tags_all          = {
          + "KubespotEnvironment" = "axiom-prod"
        }
        # (2 unchanged attributes hidden)
    }

  # module.opszero-eks.aws_cloudwatch_metric_alarm.nodes_blue_cpu_threshold will be updated in-place
  ~ resource "aws_cloudwatch_metric_alarm" "nodes_blue_cpu_threshold" {
        id                        = "axiom-prod-nodes-blue-cpu-threshold"
      ~ tags                      = {
          + "KubespotEnvironment" = "axiom-prod"
        }
      ~ tags_all                  = {
          + "KubespotEnvironment" = "axiom-prod"
        }
        # (17 unchanged attributes hidden)
    }

  # module.opszero-eks.aws_cloudwatch_metric_alarm.nodes_green_cpu_threshold will be updated in-place
  ~ resource "aws_cloudwatch_metric_alarm" "nodes_green_cpu_threshold" {
        id                        = "axiom-prod-nodes-green-cpu-threshold"
      ~ tags                      = {
          + "KubespotEnvironment" = "axiom-prod"
        }
      ~ tags_all                  = {
          + "KubespotEnvironment" = "axiom-prod"
        }
        # (17 unchanged attributes hidden)
    }

  # module.opszero-eks.aws_db_subnet_group.default will be updated in-place
  ~ resource "aws_db_subnet_group" "default" {
        id          = "axiom-prod"
        name        = "axiom-prod"
      ~ tags        = {
          + "KubespotEnvironment" = "axiom-prod"
        }
      ~ tags_all    = {
          + "KubespotEnvironment" = "axiom-prod"
        }
        # (3 unchanged attributes hidden)
    }

  # module.opszero-eks.aws_eks_addon.core["coredns"] is tainted, so must be replaced
-/+ resource "aws_eks_addon" "core" {
      ~ addon_version     = "v1.8.3-eksbuild.1" -> (known after apply)
      ~ arn               = "arn:aws:eks:us-east-1:746153586031:addon/axiom-prod/coredns/7cbcd790-f02f-08b3-6974-413920b7faf5" -> (known after apply)
      ~ created_at        = "2021-05-27T18:41:43Z" -> (known after apply)
      ~ id                = "axiom-prod:coredns" -> (known after apply)
      ~ modified_at       = "2021-05-27T20:01:02Z" -> (known after apply)
      - tags              = {} -> null
      ~ tags_all          = {} -> (known after apply)
        # (3 unchanged attributes hidden)
    }

  # module.opszero-eks.aws_eks_cluster.cluster will be updated in-place
  ~ resource "aws_eks_cluster" "cluster" {
        id                        = "axiom-prod"
        name                      = "axiom-prod"
      ~ tags                      = {
          + "KubespotEnvironment" = "axiom-prod"
        }
      ~ tags_all                  = {
          + "KubespotEnvironment" = "axiom-prod"
        }
        # (10 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # module.opszero-eks.aws_eks_fargate_profile.fargate will be updated in-place
  ~ resource "aws_eks_fargate_profile" "fargate" {
        id                     = "axiom-prod:axiom-prod-fargate"
      ~ tags                   = {
          + "KubespotEnvironment" = "axiom-prod"
        }
      ~ t [...]

2021-05-27 21:30 UTC, abhiyerra requested changes

2021-05-27 21:30 UTC, abhiyerra commented on eks/bastion.tf
> +    "KubespotEnvironment" = var.environment_name
Make the two match:

Add the quotes around Name. `"Name"`

2021-05-27 21:30 UTC, abhiyerra commented on eks/public_subnet.tf
> +    "KubespotEnvironment" = var.environment_name
Same as above comment.

2021-05-27 21:30 UTC, abhiyerra commented on eks/public_subnet.tf
> +    Name                  = "${var.environment_name}-public-${count.index}"
Same as above comment.

2021-05-28 07:03 UTC, janavenkat commented on eks/public_subnet.tf
> +    Name                  = "${var.environment_name}-public-${count.index}"
Thanks fixed

2021-05-28 15:38 UTC, abhiyerra approved these changes

2021-05-28 15:38 UTC, merged