Helm chart metrics server
opszero/kubespot pull request #162
Opened 2021-08-27 15:22 UTC by janajs

There is no official helm chart for metrics, so it's good to use the metrics server helm chart from bitnami

2021-09-01 23:14 UTC, abhiyerra requested changes

2021-09-01 23:14 UTC, abhiyerra commented on eks/variables.tf
> +variable "metrics_server" {
`merrics_server_enabled`

2021-09-02 02:36 UTC, janajs commented on eks/metrics-server.tf
> +data "aws_region" "current" {
my bad fixed

2021-09-02 06:09 UTC, abhiyerra requested changes

2021-09-02 06:09 UTC, abhiyerra commented on eks/variables.tf
> +variable "merrics_server_enabled" {
Misspelled metrics

2021-09-07 00:57 UTC, merged

2021-09-07 05:33 UTC, vijaygadde commented
@abhiyerra

╷
│ Error: Invalid reference
│
│   on .terraform/modules/opszero-eks/eks/metrics-server.tf line 3, in resource "helm_release" "metrics-server":
│    3:   name       = metrics-server
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.